/** VERIFIED_FACTS — the only scientific claims the private comms console may use.
 *  Pure data, no imports. Every fact points at a frozen DEEPSIFT source; `evidence` entries are re-checked against those
 *  files by tests/comms-facts.test.ts (JSON value at a path, formatted exactly as quoted, or an exact passage in a document).
 *  Nothing here is recomputed or new: values are copied from docs/public-claims-checklist.md and the frozen artifacts. */

export type FactCategory =
  | "FINAL_RESULT"
  | "GENERALIZATION"
  | "NEGATIVE_RESULT"
  | "METHODOLOGY"
  | "REPRODUCIBILITY"
  | "ENGINEERING"
  | "LIMITATION"
  | "CONTEXT";

/** How a frozen JSON number is quoted publicly. */
export type Fmt = "pct1" | "pct0" | "m2" | "f2" | "f3" | "m0" | "sf3" | "int" | "intc" | "raw" | "x2";

export type Evidence =
  | { file: string; path: (string | number)[]; fmt: Fmt; expect: string }
  | { file: string; contains: string };

export interface VerifiedFact {
  id: string;
  category: FactCategory;
  short_claim: string;
  exact_value?: string;
  /** Number tokens this fact licenses in a post (as written publicly). */
  numbers: string[];
  source_file: string;
  source_field_or_section: string;
  safe_public_wording: string;
  scope: string;
  limitations: string;
  forbidden_wording: string[];
  evidence: Evidence[];
}

export const FINAL_RUN = "artifacts/phase3_final/20260926T174018-phase3-final-test-e4e2";
const RESULTS = `${FINAL_RUN}/results.json`;
const DATASET = `${FINAL_RUN}/dataset_report.json`;
const REL = "apps/web/data/release.json";
const MC = "apps/web/data/mission-control.json";
const PAPER = "docs/deepsift-paper.md";
const CHECKLIST = "docs/public-claims-checklist.md";
const LIMITS = "apps/web/app/limitations/page.tsx";

const HELD_OUT_SCOPE = "Retrospective replay of archived Curiosity Navcam data, held-out test sols 950–979, 12 traverse sequences, Scheduler V3 + POSITION at 1/4 retention.";
const HEADLINE_LIMITS = "Archived (already-downlinked) PDS observations only; one rover, one camera; geometric coverage is not scientific value; no flight hardware; not NASA/JPL-validated.";
const NO_BANDWIDTH_SAVINGS = ["DEEPSIFT reduced Curiosity bandwidth by 74%", "NASA could save 74% bandwidth", "DEEPSIFT preserves 100% scientific value"];

export const VERIFIED_FACTS: VerifiedFact[] = [
  // ───────────────────────── FINAL HELD-OUT RESULT ─────────────────────────
  {
    id: "held_out_bytes",
    category: "FINAL_RESULT",
    short_claim: "Position-based sampling used 26.1% of the SEND ALL full-quality traverse baseline.",
    exact_value: "26.1%",
    numbers: ["26.1%", "0.261"],
    source_file: RESULTS,
    source_field_or_section: "primary.metrics.bytes_fraction (checklist #1)",
    safe_public_wording: "On the held-out Curiosity Navcam test, POSITION used 26.1% of the SEND ALL full-quality traverse baseline.",
    scope: HELD_OUT_SCOPE,
    limitations: `${HEADLINE_LIMITS} Frames not kept at full quality are still sent as thumbnail pairs (counted in the 26.1%).`,
    forbidden_wording: [...NO_BANDWIDTH_SAVINGS, "74% less bandwidth", "saves 74%"],
    evidence: [{ file: RESULTS, path: ["primary", "metrics", "bytes_fraction"], fmt: "pct1", expect: "26.1%" }],
  },
  {
    id: "held_out_coverage",
    category: "FINAL_RESULT",
    short_claim: "Every archived traverse frame stayed within 5 m of a kept frame (5 m coverage 1.000).",
    exact_value: "100% (1.000)",
    numbers: ["100%", "1.000", "5 m"],
    source_file: RESULTS,
    source_field_or_section: "primary.metrics.coverage_5m (checklist #2, #3)",
    safe_public_wording: "On the held-out test, 100% of archived traverse frames were within 5 m of a frame kept at full quality.",
    scope: HELD_OUT_SCOPE,
    limitations: `Spatial coverage is geometric, not a measure of scientific value. ${HEADLINE_LIMITS}`,
    forbidden_wording: ["100% of the science", "nothing was lost", "complete scientific coverage", "full scientific coverage"],
    evidence: [{ file: RESULTS, path: ["primary", "metrics", "coverage_5m"], fmt: "f3", expect: "1.000" }],
  },
  {
    id: "held_out_max_distance",
    category: "FINAL_RESULT",
    short_claim: "No archived traverse frame was more than 2.05 m from a kept frame.",
    exact_value: "2.05 m",
    numbers: ["2.05 m", "10 m"],
    source_file: RESULTS,
    source_field_or_section: "primary.metrics.max_distance_to_kept_m_worst (checklist #4)",
    safe_public_wording: "On the held-out test, the largest distance from any archived traverse frame to a kept frame was 2.05 m (pre-registered limit: 10 m).",
    scope: HELD_OUT_SCOPE,
    limitations: "Positions are PLACES interpolations (mostly the nearest pose within a drive), so distances inherit that resolution.",
    forbidden_wording: ["centimetre precision", "exact rover position"],
    evidence: [
      { file: RESULTS, path: ["primary", "metrics", "max_distance_to_kept_m_worst"], fmt: "m2", expect: "2.05 m" },
      { file: `config/phase3_final_test_config.json`, contains: "≤ 10 m in every qualifying sequence" },
    ],
  },
  {
    id: "held_out_stereo",
    category: "FINAL_RESULT",
    short_claim: "0 broken stereo pairs; 174 stereo pairs kept whole at full quality.",
    exact_value: "0 broken · 174 kept whole",
    numbers: ["0", "174"],
    source_file: RESULTS,
    source_field_or_section: "primary.metrics.stereo_broken / stereo_kept_full (checklist #5, #6)",
    safe_public_wording: "On the held-out test, no stereo pair was split: 174 pairs were kept whole at full quality and 0 were broken.",
    scope: HELD_OUT_SCOPE,
    limitations: "Stereo integrity is a scheduling property; it does not measure the scientific use of each pair.",
    forbidden_wording: ["perfect 3D reconstruction", "all stereo data preserved"],
    evidence: [
      { file: RESULTS, path: ["primary", "metrics", "stereo_broken"], fmt: "int", expect: "0" },
      { file: RESULTS, path: ["primary", "metrics", "stereo_kept_full"], fmt: "int", expect: "174" },
    ],
  },
  {
    id: "held_out_retention",
    category: "FINAL_RESULT",
    short_claim: "The primary operating point keeps 1/4 of traverse frames at full quality; the rest go down as thumbnails.",
    exact_value: "1/4 (0.25)",
    numbers: ["1/4", "0.25", "25%"],
    source_file: "config/phase3_final_test_config.json",
    source_field_or_section: "evaluation.primary_fraction (checklist #10)",
    safe_public_wording: "DEEPSIFT kept 1/4 of traverse frames at full quality; every other frame was still sent as a thumbnail pair.",
    scope: HELD_OUT_SCOPE,
    limitations: "Frame retention is a simulated budget on archived data, not an onboard storage decision.",
    forbidden_wording: ["deleted 75% of images", "threw away 3/4 of the images"],
    evidence: [{ file: "config/phase3_final_test_config.json", path: ["evaluation", "primary_fraction"], fmt: "raw", expect: "0.25" }],
  },
  {
    id: "held_out_pass",
    category: "FINAL_RESULT",
    short_claim: "The pre-registered primary criterion PASSED on the held-out test (bytes ≤ 0.35, coverage ≥ 0.90, ≤ 10 m, 0 broken pairs).",
    exact_value: "PASS",
    numbers: ["0.35", "0.90", "10 m", "0"],
    source_file: RESULTS,
    source_field_or_section: "primary.RESULT (checklist #7, #11, #12)",
    safe_public_wording: "The held-out test was a binary pre-registered criterion, and it passed.",
    scope: HELD_OUT_SCOPE,
    limitations: "A pass on one held-out interval of one camera; not evidence of flight readiness.",
    forbidden_wording: ["proven", "validated for flight", "mission-ready"],
    evidence: [
      { file: RESULTS, path: ["primary", "RESULT"], fmt: "raw", expect: "PASS" },
      { file: "config/phase3_final_test_config.json", path: ["primary", "PASS_iff_all", "P1"], fmt: "raw", expect: "bytes fraction ≤ 0.35 of SEND_ALL" },
    ],
  },
  {
    id: "held_out_dataset",
    category: "FINAL_RESULT",
    short_claim: "Held-out interval: Curiosity Navcam sols 950–979 — 25 active sols, 1,194 acquisitions, 4,342 PDS products, 12 traverses, 679 traverse frames.",
    exact_value: "sols 950–979 · 12 traverses · 679 frames",
    numbers: ["950", "979", "25", "1,194", "4,342", "12", "679"],
    source_file: DATASET,
    source_field_or_section: "n_active_sols, acquisitions, products, traverse_sequences_ge_10_frames, traverse_frames (checklist #14–18)",
    safe_public_wording: "The held-out test covered Curiosity Navcam sols 950–979: 12 traverse sequences, 679 archived traverse frames.",
    scope: "Archived Navcam products in the PDS for that sol window only.",
    limitations: "Only what was downlinked and archived exists in the PDS.",
    forbidden_wording: ["every image Curiosity took", "the full onboard stream"],
    evidence: [
      { file: DATASET, path: ["n_active_sols"], fmt: "int", expect: "25" },
      { file: DATASET, path: ["acquisitions"], fmt: "intc", expect: "1,194" },
      { file: DATASET, path: ["products"], fmt: "intc", expect: "4,342" },
      { file: DATASET, path: ["traverse_sequences_ge_10_frames"], fmt: "int", expect: "12" },
      { file: DATASET, path: ["traverse_frames"], fmt: "int", expect: "679" },
    ],
  },
  {
    id: "method_comparison",
    category: "FINAL_RESULT",
    short_claim: "At the same ~26% of bytes, keeping every 4th frame (EVERY_NTH) left a frame 20.04 m from anything kept; POSITION's worst case was 2.05 m.",
    exact_value: "EVERY_NTH 20.04 m vs POSITION 2.05 m (UNIFORM_DISTANCE 3.03 m, POSITION+EMBEDDING 4.89 m)",
    numbers: ["20.04 m", "2.05 m", "3.03 m", "4.89 m", "0.261", "0.260", "0.257", "0.996", "26.1%"],
    source_file: RESULTS,
    source_field_or_section: "traverse.summary.0.25|* (checklist #23, #24; paper Table 3)",
    safe_public_wording: "On the held-out test at 1/4 retention, keeping every Nth frame left one archived frame 20.04 m from any kept frame; position-based sampling kept the worst case at 2.05 m for about the same bytes.",
    scope: HELD_OUT_SCOPE,
    limitations: "EVERY_NTH drops whole rover stops on these traverses; a different acquisition pattern could change the comparison.",
    forbidden_wording: ["10x better", "ten times better"],
    evidence: [
      { file: RESULTS, path: ["traverse", "summary", "0.25|EVERY_NTH_FRAME", "max_distance_to_kept_m_worst"], fmt: "m2", expect: "20.04 m" },
      { file: RESULTS, path: ["traverse", "summary", "0.25|UNIFORM_DISTANCE", "max_distance_to_kept_m_worst"], fmt: "m2", expect: "3.03 m" },
      { file: RESULTS, path: ["traverse", "summary", "0.25|POSITION_PLUS_EMBEDDING_CHANGE", "max_distance_to_kept_m_worst"], fmt: "m2", expect: "4.89 m" },
      { file: RESULTS, path: ["traverse", "summary", "0.25|EVERY_NTH_FRAME", "coverage_5m"], fmt: "f3", expect: "0.996" },
    ],
  },
  {
    id: "operating_points",
    category: "FINAL_RESULT",
    short_claim: "Other retention levels on the held-out test: 1/2 → 51.4% of bytes (max 1.00 m); 1/8 → 13.8% of bytes, 98.3% 5 m coverage (max 6.53 m).",
    exact_value: "1/2: 51.4%, 1.00 m · 1/8: 13.8%, 98.3%, 6.53 m",
    numbers: ["1/2", "51.4%", "1.00 m", "1/8", "13.8%", "98.3%", "6.53 m"],
    source_file: MC,
    source_field_or_section: "operating_points.0.5 / operating_points.0.125 (from results.json traverse.summary)",
    safe_public_wording: "Halving retention again (1/8) used 13.8% of the bytes but coverage dropped to 98.3% and the worst distance rose to 6.53 m — the trade-off is visible, not free.",
    scope: `${HELD_OUT_SCOPE.replace(" at 1/4 retention", "")} Only 1/4 was the pre-registered primary point; 1/2 and 1/8 are descriptive.`,
    limitations: "1/2 and 1/8 were not pass/fail criteria.",
    forbidden_wording: ["1/8 also passed"],
    evidence: [
      { file: MC, path: ["operating_points", "0.5", "bytes_fraction"], fmt: "pct1", expect: "51.4%" },
      { file: MC, path: ["operating_points", "0.5", "max_distance_to_kept_m_worst"], fmt: "m2", expect: "1.00 m" },
      { file: MC, path: ["operating_points", "0.125", "bytes_fraction"], fmt: "pct1", expect: "13.8%" },
      { file: MC, path: ["operating_points", "0.125", "coverage_5m"], fmt: "pct1", expect: "98.3%" },
      { file: MC, path: ["operating_points", "0.125", "max_distance_to_kept_m_worst"], fmt: "m2", expect: "6.53 m" },
    ],
  },
  {
    id: "example_traverse",
    category: "CONTEXT",
    short_claim: "Example held-out traverse 967:trav00327: 105 archived frames over 89 m, chosen as the longest path (not claimed representative).",
    exact_value: "105 frames · 89 m",
    numbers: ["967", "105", "89 m"],
    source_file: MC,
    source_field_or_section: "representative + traverses[967:trav00327].frames_count / length_m",
    safe_public_wording: "An example held-out traverse (the longest one, not a statistically representative pick): 105 archived Navcam frames over 89 m.",
    scope: "One traverse from the held-out interval, chosen by a fixed rule (longest path).",
    limitations: "Not statistically representative of all traverses.",
    forbidden_wording: ["representative traverse", "typical traverse"],
    evidence: [
      { file: MC, path: ["representative"], fmt: "raw", expect: "967:trav00327" },
      { file: MC, path: ["traverses", 9, "sequence"], fmt: "raw", expect: "967:trav00327" },
      { file: MC, path: ["traverses", 9, "frames_count"], fmt: "int", expect: "105" },
      { file: MC, path: ["traverses", 9, "length_m"], fmt: "m0", expect: "89 m" },
    ],
  },
  {
    id: "scheduler_v3",
    category: "ENGINEERING",
    short_claim: "Scheduler V3 had 0 monotonicity violations and 0 single-eye stereo pairs on the held-out test.",
    exact_value: "0 / 0",
    numbers: ["0"],
    source_file: RESULTS,
    source_field_or_section: "scheduler_v3.total_violations / single_eye_usable_violations (checklist #8, #9)",
    safe_public_wording: "The stereo-safe scheduler never let coverage fall as the budget grew, and never sent one eye of a stereo pair alone: 0 violations on the held-out test.",
    scope: "Held-out test, simulated budgets on archived data.",
    limitations: "Its compressed stereo tier is a simulated product (DEEPSIFT's own JPEG q50 re-encoding), not a NASA flight product.",
    forbidden_wording: ["flight scheduler", "used onboard"],
    evidence: [
      { file: RESULTS, path: ["scheduler_v3", "total_violations"], fmt: "int", expect: "0" },
      { file: RESULTS, path: ["scheduler_v3", "single_eye_usable_violations"], fmt: "int", expect: "0" },
    ],
  },
  {
    id: "scheduler_history",
    category: "ENGINEERING",
    short_claim: "The first greedy scheduler was non-monotonic (more budget could reduce coverage); the next broke stereo (its compressed tier carried one eye). V3 fixed both.",
    numbers: [],
    source_file: PAPER,
    source_field_or_section: "§7 Phase 3.0–3.1 and §11 Negative results",
    safe_public_wording: "Our first scheduler had a bug in its logic: giving it more bandwidth could reduce coverage. The fix broke stereo pairs. The third version fixed both.",
    scope: "Development period (sols 412–430).",
    limitations: "Scheduler properties were checked on simulated budgets, not on flight software.",
    forbidden_wording: [],
    evidence: [
      { file: PAPER, contains: "A first greedy scheduler was found to be non-monotonic: more budget could reduce coverage." },
      { file: PAPER, contains: "A progressive replacement fixed monotonicity but broke stereo, because its compressed tier carried one eye." },
    ],
  },
  {
    id: "thumbnails_sent",
    category: "ENGINEERING",
    short_claim: "Frames that are not kept are not dropped: they are still sent as thumbnail pairs, and those bytes are counted.",
    numbers: [],
    source_file: PAPER,
    source_field_or_section: "§5 Traverse metrics (bytes definition) and §4 Scheduler V3",
    safe_public_wording: "Nothing is thrown away in the replay: frames that are not kept at full quality still go down as thumbnail pairs, and their bytes count toward the total.",
    scope: "Traverse byte accounting in the replay.",
    limitations: "Byte costs are PDS label estimates, not flight packetization.",
    forbidden_wording: ["deleted", "discarded images"],
    evidence: [{ file: PAPER, contains: "kept frames sent as full pairs, the others as thumbnail\n  pairs" }],
  },
  {
    id: "distance_metric",
    category: "METHODOLOGY",
    short_claim: "Gap metrics measured the rover's drive step, not the selection (median native spacing 0 m; stops ~19.5 m apart), so the study switched to 'largest distance to a kept frame'.",
    numbers: ["0 m", "19.5 m", "20 m", "10 m"],
    source_file: PAPER,
    source_field_or_section: "§5 'Why largest distance to a kept frame rather than a gap metric'",
    safe_public_wording: "Frames cluster at rover stops about 19.5 m apart, so gap metrics mostly measured how the rover drove. We switched to the distance from every archived frame to its nearest kept frame.",
    scope: "Metric chosen on development data only.",
    limitations: "The change was prompted by a validation-1 failure and fixed before fresh data was seen.",
    forbidden_wording: [],
    evidence: [{ file: PAPER, contains: "stops were about 19.5 m apart" }],
  },

  // ───────────────────────── GENERALIZATION ─────────────────────────
  {
    id: "four_periods",
    category: "GENERALIZATION",
    short_claim: "Four separate, never-pooled periods: development (sols 412–430), validation 1 (779–820), validation 2 (1100–1129), held-out test (950–979).",
    numbers: ["412", "430", "779", "820", "1100", "1129", "950", "979"],
    source_file: REL,
    source_field_or_section: "reproducibility.periods",
    safe_public_wording: "The method was tuned on one period, checked on two others, and tested once on a fourth. The periods were never pooled.",
    scope: "Curiosity Navcam traverse sequences in four sol windows.",
    limitations: "Four windows of one rover's mission.",
    forbidden_wording: ["across the whole mission", "all of Curiosity's traverses"],
    evidence: [
      { file: REL, path: ["reproducibility", "periods", 0, "sols", 0], fmt: "int", expect: "412" },
      { file: REL, path: ["reproducibility", "periods", 1, "sols", 0], fmt: "int", expect: "779" },
      { file: REL, path: ["reproducibility", "periods", 2, "sols", 1], fmt: "int", expect: "1129" },
      { file: REL, path: ["reproducibility", "periods", 3, "sols", 0], fmt: "int", expect: "950" },
    ],
  },
  {
    id: "four_period_coverage",
    category: "GENERALIZATION",
    short_claim: "POSITION at 1/4 kept 5 m coverage at 1.000 in all four periods, with 0 broken stereo pairs.",
    exact_value: "1.000 · 1.000 · 1.000 · 1.000",
    numbers: ["1.000", "100%", "5 m", "0"],
    source_file: RESULTS,
    source_field_or_section: "four_period.*.POSITION.coverage_5m (checklist #29–31)",
    safe_public_wording: "Same method, four separate periods: 5 m coverage was 1.000 in every one.",
    scope: "Development, validation 1, validation 2 and held-out test; POSITION at 1/4.",
    limitations: "Only the test period is a clean held-out result; development was used for tuning.",
    forbidden_wording: ["works everywhere", "generalizes to any rover"],
    evidence: [
      { file: RESULTS, path: ["four_period", "DEVELOPMENT 412–430", "POSITION", "coverage_5m"], fmt: "f3", expect: "1.000" },
      { file: RESULTS, path: ["four_period", "VALIDATION1 779–820", "POSITION", "coverage_5m"], fmt: "f3", expect: "1.000" },
      { file: RESULTS, path: ["four_period", "VALIDATION2 1100–1129", "POSITION", "coverage_5m"], fmt: "f3", expect: "1.000" },
    ],
  },
  {
    id: "four_period_bytes",
    category: "GENERALIZATION",
    short_claim: "POSITION bytes at 1/4 across the four periods: 0.266, 0.265, 0.270, 0.261 of full quality.",
    exact_value: "0.266 / 0.265 / 0.270 / 0.261",
    numbers: ["0.266", "0.265", "0.270", "0.261"],
    source_file: RESULTS,
    source_field_or_section: "four_period.*.POSITION.bytes_fraction (checklist #35–37, #1)",
    safe_public_wording: "Byte cost at 1/4 barely moved between periods: 0.266, 0.265, 0.270 and 0.261 of the full-quality baseline.",
    scope: "Four periods; POSITION at 1/4.",
    limitations: HEADLINE_LIMITS,
    forbidden_wording: [],
    evidence: [
      { file: RESULTS, path: ["four_period", "DEVELOPMENT 412–430", "POSITION", "bytes_fraction"], fmt: "f3", expect: "0.266" },
      { file: RESULTS, path: ["four_period", "VALIDATION1 779–820", "POSITION", "bytes_fraction"], fmt: "f3", expect: "0.265" },
      { file: RESULTS, path: ["four_period", "VALIDATION2 1100–1129", "POSITION", "bytes_fraction"], fmt: "f3", expect: "0.270" },
    ],
  },
  {
    id: "four_period_distance",
    category: "GENERALIZATION",
    short_claim: "POSITION's largest distance to a kept frame: 2.64, 2.78, 1.94 and 2.05 m across the four periods.",
    exact_value: "2.64 / 2.78 / 1.94 / 2.05 m",
    numbers: ["2.64 m", "2.78 m", "1.94 m", "2.05 m", "2.64", "2.78", "1.94", "2.05"],
    source_file: RESULTS,
    source_field_or_section: "four_period.*.POSITION.max_distance_to_kept_m_worst (checklist #32–34, #4)",
    safe_public_wording: "In all four periods, no archived frame was more than 2.78 m from a kept one (2.64 / 2.78 / 1.94 / 2.05 m).",
    scope: "Four periods; POSITION at 1/4.",
    limitations: "PLACES-interpolated positions.",
    forbidden_wording: [],
    evidence: [
      { file: RESULTS, path: ["four_period", "DEVELOPMENT 412–430", "POSITION", "max_distance_to_kept_m_worst"], fmt: "m2", expect: "2.64 m" },
      { file: RESULTS, path: ["four_period", "VALIDATION1 779–820", "POSITION", "max_distance_to_kept_m_worst"], fmt: "m2", expect: "2.78 m" },
      { file: RESULTS, path: ["four_period", "VALIDATION2 1100–1129", "POSITION", "max_distance_to_kept_m_worst"], fmt: "m2", expect: "1.94 m" },
    ],
  },

  // ───────────────────────── NEGATIVE RESULTS ─────────────────────────
  {
    id: "jev_ranking",
    category: "NEGATIVE_RESULT",
    short_claim: "The semantic model (Jev) gave no measurable ranking improvement in its tested role: AUROC +0.006 vs deterministic rules (95% CI −0.020 to +0.037), 1,500 live calls.",
    exact_value: "+0.006 (95% CI −0.020 to +0.037)",
    numbers: ["+0.006", "-0.020", "+0.037", "1,500", "95%"],
    source_file: "apps/web/data/home-summary.json",
    source_field_or_section: "jev.auroc_diff_vs_rules.with_objective, jev.live_calls (checklist #38–41)",
    safe_public_wording: "In its tested role — re-ranking already-detected REMS/RAD events — the semantic model gave no measurable improvement over deterministic rules (AUROC +0.006, 95% CI −0.020 to +0.037).",
    scope: "Phase 2; ranking candidates surfaced by a frozen deterministic detector; one model, one role.",
    limitations: "Specific to the tested role; not a general claim about the model or about LLMs.",
    forbidden_wording: ["LLMs are useless", "AI doesn't work", "the model is bad"],
    evidence: [
      { file: "apps/web/data/home-summary.json", path: ["jev", "auroc_diff_vs_rules", "with_objective", "diff"], fmt: "sf3", expect: "+0.006" },
      { file: "apps/web/data/home-summary.json", path: ["jev", "auroc_diff_vs_rules", "with_objective", "ci95", 0], fmt: "sf3", expect: "-0.020" },
      { file: "apps/web/data/home-summary.json", path: ["jev", "auroc_diff_vs_rules", "with_objective", "ci95", 1], fmt: "sf3", expect: "+0.037" },
      { file: "apps/web/data/home-summary.json", path: ["jev", "live_calls"], fmt: "intc", expect: "1,500" },
    ],
  },
  {
    id: "telemetry_ranking",
    category: "NEGATIVE_RESULT",
    short_claim: "Telemetry-driven image ranking had no measurable image-selection value: at a 1% budget it made 7 acquisitions usable at 1 rover position — the fewest of six strategies.",
    exact_value: "7 acquisitions · 1 position at 1%",
    numbers: ["1%", "7", "1", "6"],
    source_file: "artifacts/phase3_2/20260925T135920-phase3.2-dev-corrective-ceb8/results.json",
    source_field_or_section: "schedulers.comparison.V3|TELEMETRY-PRIORITY|0.01 (checklist #42, #43)",
    safe_public_wording: "Ranking images by environmental telemetry didn't help pick images: it ignores image content by construction, and at a 1% budget it covered a single rover position.",
    scope: "Development period, Scheduler V3.",
    limitations: "Telemetry may still matter for other decisions; this tested image selection only.",
    forbidden_wording: ["telemetry is useless"],
    evidence: [
      { file: "artifacts/phase3_2/20260925T135920-phase3.2-dev-corrective-ceb8/results.json", path: ["schedulers", "comparison", "V3|TELEMETRY-PRIORITY|0.01", "acquisitions_usable"], fmt: "int", expect: "7" },
      { file: "artifacts/phase3_2/20260925T135920-phase3.2-dev-corrective-ceb8/results.json", path: ["schedulers", "comparison", "V3|TELEMETRY-PRIORITY|0.01", "rover_positions_usable"], fmt: "int", expect: "1" },
    ],
  },
  {
    id: "phash_failed",
    category: "NEGATIVE_RESULT",
    short_claim: "Constrained perceptual hashing failed validation: false-merge rate 0.15–0.19 vs a 0.05 limit, and at most 1.03× traverse compression.",
    exact_value: "0.15–0.19 false merge · ≤ 1.03×",
    numbers: ["0.15", "0.19", "0.05", "1.03×"],
    source_file: "artifacts/phase3_3/20260926T142033-phase3.3-val-2a31/results.json",
    source_field_or_section: "phash.PHASH_PLUS_* (checklist #46–48)",
    safe_public_wording: "Image fingerprints (pHash) merged different scenes 15–19% of the time on validation (limit: 5%) and saved almost nothing (≤ 1.03×). Dropped.",
    scope: "Validation 1 (sols 779–820).",
    limitations: "Specific to the tested constrained pHash variants.",
    forbidden_wording: [],
    evidence: [
      { file: "artifacts/phase3_3/20260926T142033-phase3.3-val-2a31/results.json", path: ["phash", "PHASH_PLUS_TIME_120S", "false_merge_rate_different_scene"], fmt: "f2", expect: "0.15" },
      { file: "artifacts/phase3_3/20260926T142033-phase3.3-val-2a31/results.json", path: ["phash", "PHASH_PLUS_SAME_ROVER_STOP", "false_merge_rate_different_scene"], fmt: "f2", expect: "0.19" },
      { file: "artifacts/phase3_3/20260926T142033-phase3.3-val-2a31/results.json", path: ["phash", "PHASH_PLUS_TIME_120S", "traverse_compression"], fmt: "x2", expect: "1.03×" },
    ],
  },
  {
    id: "quality_v2_failed",
    category: "NEGATIVE_RESULT",
    short_claim: "The learned quality detector (QUALITY_V2) failed validation: false-positive rate 3.6% in development → 10.6% on validation 1.",
    exact_value: "3.6% → 10.6%",
    numbers: ["3.6%", "10.6%", "43%", "2.2%"],
    source_file: "artifacts/phase3_3/20260926T142033-phase3.3-val-2a31/results.json",
    source_field_or_section: "quality_v2_real.development_fpr / overall (checklist #44, #45); paper §8",
    safe_public_wording: "A learned image-quality check looked fine in development (3.6% false positives) and tripled out of sample (10.6%), mostly on upward-pointing, low-texture frames. It was kept only as a diagnostic flag.",
    scope: "Validation 1 (sols 779–820).",
    limitations: "A new orientation-aware detector would need a new, untouched validation interval.",
    forbidden_wording: ["image quality detection doesn't work"],
    evidence: [
      { file: "artifacts/phase3_3/20260926T142033-phase3.3-val-2a31/results.json", path: ["quality_v2_real", "development_fpr"], fmt: "pct1", expect: "3.6%" },
      { file: PAPER, contains: "43 % flagged above the horizon against 2.2 % at or below it" },
    ],
  },
  {
    id: "embedding_gain",
    category: "NEGATIVE_RESULT",
    short_claim: "Embedding-assisted selection gained +0.044 visual-change coverage in development, then +0.004, +0.001, +0.005 — below the pre-registered +0.020 threshold.",
    exact_value: "+0.044 → +0.004 / +0.001 / +0.005 (threshold 0.020)",
    numbers: ["+0.044", "+0.004", "+0.001", "+0.005", "0.020", "+0.020"],
    source_file: RESULTS,
    source_field_or_section: "four_period.*.embedding_gain.visual_change_gain (checklist #25–28)",
    safe_public_wording: "Image embeddings looked helpful in development (+0.044). Outside it: +0.004, +0.001, +0.005, against a pre-registered +0.020 bar. No meaningful added selection value.",
    scope: "POSITION + EMBEDDING vs POSITION at 1/4, four periods.",
    limitations: "Visual-change coverage is an embedding proxy, not a measure of scientific value.",
    forbidden_wording: ["embeddings are useless", "deep learning failed"],
    evidence: [
      { file: RESULTS, path: ["four_period", "DEVELOPMENT 412–430", "embedding_gain", "visual_change_gain"], fmt: "sf3", expect: "+0.044" },
      { file: RESULTS, path: ["four_period", "VALIDATION1 779–820", "embedding_gain", "visual_change_gain"], fmt: "sf3", expect: "+0.004" },
      { file: RESULTS, path: ["four_period", "VALIDATION2 1100–1129", "embedding_gain", "visual_change_gain"], fmt: "sf3", expect: "+0.001" },
      { file: RESULTS, path: ["four_period", "TEST 950–979", "embedding_gain", "visual_change_gain"], fmt: "sf3", expect: "+0.005" },
    ],
  },
  {
    id: "embedding_final",
    category: "NEGATIVE_RESULT",
    short_claim: "Held-out secondary question: visual-change coverage 0.950 (POSITION) vs 0.956 (POSITION + EMBEDDING) — NO MEASURABLE ADDED VALUE.",
    exact_value: "0.950 vs 0.956",
    numbers: ["0.950", "0.956", "+0.005"],
    source_file: RESULTS,
    source_field_or_section: "secondary_embedding (checklist #19–22)",
    safe_public_wording: "On the held-out test, adding image embeddings moved a visual-change proxy from 0.950 to 0.956: positive, but about a quarter of the pre-registered bar.",
    scope: "Held-out test, 1/4 retention.",
    limitations: "Visual-change coverage is a MobileNetV2 proxy, not scientific value.",
    forbidden_wording: [],
    evidence: [
      { file: RESULTS, path: ["secondary_embedding", "position_visual_1_4"], fmt: "f3", expect: "0.950" },
      { file: RESULTS, path: ["secondary_embedding", "position_plus_embedding_visual_1_4"], fmt: "f3", expect: "0.956" },
      { file: RESULTS, path: ["secondary_embedding", "CONCLUSION"], fmt: "raw", expect: "NO MEASURABLE ADDED VALUE" },
    ],
  },
  {
    id: "validation1_partial",
    category: "METHODOLOGY",
    short_claim: "On validation 1, POSITION + EMBEDDING failed a density-relative worst-gap rule (limit shrank from ~39 m to 3.8 m); the verdict PARTIALLY GENERALIZES was recorded and never rewritten.",
    numbers: ["39 m", "3.8 m"],
    source_file: PAPER,
    source_field_or_section: "§8 Validation 1",
    safe_public_wording: "One of our own validation rules failed for a boring reason: it scaled with frame density. We recorded the failure, never rewrote it, and defined a better metric before touching fresh data.",
    scope: "Validation 1 (sols 779–820).",
    limitations: "The replacement metric was defined on development data.",
    forbidden_wording: [],
    evidence: [{ file: PAPER, contains: "so the relative limit shrank from about 39 m to 3.8 m. The verdict was recorded as PARTIALLY GENERALIZES and never" }],
  },

  // ───────────────────────── METHODOLOGY / REPRODUCIBILITY ─────────────────────────
  {
    id: "frozen_before_download",
    category: "METHODOLOGY",
    short_claim: "The final test config was committed to git less than 25 seconds before the first test image was written (17:03:26 vs 17:03:50 UTC).",
    exact_value: "config 17:03:26 UTC · first image 17:03:50 UTC",
    numbers: ["25", "25 seconds", "25 s", "17:03:26", "17:03:50"],
    source_file: REL,
    source_field_or_section: "reproducibility.frozen_before_download (checklist #49–51)",
    safe_public_wording: "The final test's configuration and pass/fail rule were committed to git before any test data existed on disk — less than 25 seconds before the first test image was written.",
    scope: "Final held-out test.",
    limitations: "Git timestamps are self-reported; the ordering is also checked by config hash and file-system timestamps.",
    forbidden_wording: [],
    evidence: [
      { file: REL, path: ["reproducibility", "frozen_before_download", "config_commit_time"], fmt: "raw", expect: "2026-09-26T13:03:26-04:00" },
      { file: CHECKLIST, contains: "| 51 | First test image written (UTC) | **2026-09-26T17:03:50** | ✅ |" },
    ],
  },
  {
    id: "preregistration",
    category: "METHODOLOGY",
    short_claim: "Every configuration and pass/fail rule was committed to git before the data that tested it was downloaded; runners refuse to start if a hash differs.",
    numbers: [],
    source_file: PAPER,
    source_field_or_section: "§5 Experimental design",
    safe_public_wording: "Every stage followed the same rule: write down the config and the pass/fail criterion, commit it, and only then download the data that tests it.",
    scope: "All Phase 3 stages.",
    limitations: "Pre-registration is self-administered (git), not a third-party registry.",
    forbidden_wording: ["peer-reviewed"],
    evidence: [{ file: PAPER, contains: "Runners recompute the configuration hash and the SHA-256 of each listed source file, and refuse to start if anything\ndiffers." }],
  },
  {
    id: "test_used_once",
    category: "METHODOLOGY",
    short_claim: "The held-out test interval was analysed once; it is now used up, and any modified method needs a new untouched interval.",
    numbers: [],
    source_file: LIMITS,
    source_field_or_section: "Limitations · 'The held-out test is used up'",
    safe_public_wording: "The held-out test ran once. Nothing changed afterwards, and that interval can't be reused: any new method needs new, untouched data.",
    scope: "Final held-out test (sols 950–979).",
    limitations: "One test interval.",
    forbidden_wording: [],
    evidence: [{ file: LIMITS, contains: "The final test interval has been analysed once." }],
  },
  {
    id: "validation2_listings",
    category: "METHODOLOGY",
    short_claim: "Validation 2 (sols 1100–1129) was selected from PDS listings alone, without reading image content.",
    numbers: ["1100", "1129"],
    source_file: PAPER,
    source_field_or_section: "§3 Data (validation 2 selection rule)",
    safe_public_wording: "The second validation interval was picked from archive listings alone — before looking at a single image in it.",
    scope: "Validation 2.",
    limitations: "Listing-based selection limits, but does not eliminate, selection bias.",
    forbidden_wording: [],
    evidence: [{ file: PAPER, contains: "listings alone, without reading image content." }],
  },
  {
    id: "integrity_manifest",
    category: "REPRODUCIBILITY",
    short_claim: "70 scientific artifacts are hash-locked in an integrity manifest with an aggregate SHA-256; one command verifies them.",
    exact_value: "70 files",
    numbers: ["70", "256"],
    source_file: "docs/release/science-artifacts.json",
    source_field_or_section: "files (checklist #52)",
    safe_public_wording: "The 70 files behind the result are hash-locked; `release_integrity.py --verify` checks them.",
    scope: "DEEPSIFT v1 research release.",
    limitations: "Raw PDS products are not committed; they are re-downloadable and checked by SHA-256.",
    forbidden_wording: [],
    evidence: [{ file: "docs/release/science-artifacts.json", path: ["files"], fmt: "int", expect: "70" }],
  },
  {
    id: "config_hash",
    category: "REPRODUCIBILITY",
    short_claim: "Final test config hash 6f35d7fc…, committed before download; tag phase3-final-test-complete.",
    exact_value: "6f35d7fc",
    numbers: [],
    source_file: "config/phase3_final_test_config.json",
    source_field_or_section: "config_hash (checklist #13)",
    safe_public_wording: "Final test config: hash 6f35d7fc…, committed before the test data was downloaded.",
    scope: "Final held-out test.",
    limitations: "",
    forbidden_wording: [],
    evidence: [{ file: CHECKLIST, contains: "| 13 | Final test: config hash | **6f35d7fc** | ✅ |" }],
  },
  {
    id: "public_claims",
    category: "REPRODUCIBILITY",
    short_claim: "52 public numbers are recomputed from frozen sources by one script before anything is published.",
    exact_value: "52/52",
    numbers: ["52"],
    source_file: CHECKLIST,
    source_field_or_section: "Numerical claims table",
    safe_public_wording: "Every number we publish (52 of them) is recomputed from the frozen artifacts by a script before release.",
    scope: "DEEPSIFT v1 public materials.",
    limitations: "",
    forbidden_wording: [],
    evidence: [{ file: CHECKLIST, contains: "| 52 | Scientific artifacts under integrity manifest | **70** | ✅ |" }],
  },
  {
    id: "open_code",
    category: "REPRODUCIBILITY",
    short_claim: "Code, configs, manifests, run artifacts and the paper are public (Apache-2.0) at github.com/nassimb/deepsift, tag deepsift-v1-research.",
    numbers: ["2.0"],
    source_file: "LICENSE",
    source_field_or_section: "Apache License 2.0; README",
    safe_public_wording: "Everything is public: code, configs, dataset manifests, run artifacts and the paper (Apache-2.0).",
    scope: "DEEPSIFT v1 research release.",
    limitations: "NASA/PDS data are not covered by the code licence (see NOTICE).",
    forbidden_wording: [],
    evidence: [{ file: "LICENSE", contains: "Apache License" }],
  },

  // ───────────────────────── LIMITATIONS ─────────────────────────
  {
    id: "lim_survivorship",
    category: "LIMITATION",
    short_claim: "PDS survivorship bias: the archive only holds what the mission actually downlinked.",
    numbers: [],
    source_file: LIMITS,
    source_field_or_section: "PDS survivorship bias",
    safe_public_wording: "The public archive only contains what Curiosity already sent home. DEEPSIFT re-prioritizes those archived observations; it can't see images that were never sent.",
    scope: "All DEEPSIFT results.",
    limitations: "",
    forbidden_wording: ["every image Curiosity took"],
    evidence: [{ file: LIMITS, contains: "The Planetary Data System contains only observations the mission actually downlinked." }],
  },
  {
    id: "lim_no_onboard_stream",
    category: "LIMITATION",
    short_claim: "Archived/downlinked observations only; no reconstruction of the rover's full onboard image stream.",
    numbers: [],
    source_file: LIMITS,
    source_field_or_section: "Archived, downlinked observations only",
    safe_public_wording: "It's a retrospective replay: archived products are treated as if they were waiting onboard. It does not reconstruct what the rover actually held in storage.",
    scope: "All DEEPSIFT results.",
    limitations: "",
    forbidden_wording: ["reconstructs the onboard stream"],
    evidence: [{ file: LIMITS, contains: "it does not reconstruct what the rover actually held in storage at any time." }],
  },
  {
    id: "lim_one_rover_camera",
    category: "LIMITATION",
    short_claim: "One rover (Curiosity), one camera (Navcam), traverse sequences only, four sol windows.",
    numbers: [],
    source_file: LIMITS,
    source_field_or_section: "One rover, one camera; Limited mission windows",
    safe_public_wording: "One rover, one camera, traverse imagery only. Nothing here is tested on Mastcam, other rovers or orbiters.",
    scope: "All DEEPSIFT results.",
    limitations: "",
    forbidden_wording: ["works for any rover", "any camera"],
    evidence: [{ file: LIMITS, contains: "Curiosity Navcam only." }],
  },
  {
    id: "lim_geometry_not_science",
    category: "LIMITATION",
    short_claim: "Geometric coverage is not scientific value; visual-change coverage is an embedding proxy.",
    numbers: [],
    source_file: LIMITS,
    source_field_or_section: "Visual-change proxy ≠ scientific value",
    safe_public_wording: "Spatial coverage says every place along the route is represented. It does not say the science was preserved — only mission scientists could judge that.",
    scope: "All DEEPSIFT metrics.",
    limitations: "",
    forbidden_wording: ["preserves scientific value", "no science lost"],
    evidence: [{ file: LIMITS, contains: "neither metric measures whether science value was preserved." }],
  },
  {
    id: "lim_simulated_tier",
    category: "LIMITATION",
    short_claim: "The compressed stereo tier is a SIMULATED product tier (DEEPSIFT's own JPEG q50 re-encoding), not a NASA flight product.",
    numbers: [],
    source_file: LIMITS,
    source_field_or_section: "Simulated compressed stereo tier",
    safe_public_wording: "One of the scheduler's tiers — compressed stereo — is simulated (our own JPEG re-encoding). The traverse results use only NASA label estimates for full and thumbnail tiers.",
    scope: "Scheduler V3.",
    limitations: "",
    forbidden_wording: ["NASA compression"],
    evidence: [{ file: LIMITS, contains: "a SIMULATED PRODUCT TIER, not a NASA flight product." }],
  },
  {
    id: "lim_no_flight_hw",
    category: "LIMITATION",
    short_claim: "No flight hardware test and no power, thermal or compute-budget model; everything ran on a laptop CPU.",
    numbers: [],
    source_file: LIMITS,
    source_field_or_section: "No flight hardware test; No power, thermal or compute-budget model",
    safe_public_wording: "Everything ran on a laptop. No radiation-tolerant processor, no flight software, no power or thermal model.",
    scope: "All DEEPSIFT results.",
    limitations: "",
    forbidden_wording: ["flight-ready", "runs onboard"],
    evidence: [{ file: LIMITS, contains: "Everything ran on a laptop CPU." }],
  },
  {
    id: "lim_no_nasa",
    category: "LIMITATION",
    short_claim: "Independent research prototype: not reviewed, endorsed, used or validated by NASA, JPL or the MSL mission team.",
    numbers: [],
    source_file: LIMITS,
    source_field_or_section: "No NASA validation",
    safe_public_wording: "DEEPSIFT is independent research using NASA's public archive. It is not affiliated with, reviewed or validated by NASA or JPL.",
    scope: "All DEEPSIFT materials.",
    limitations: "",
    forbidden_wording: ["NASA-approved", "JPL-backed"],
    evidence: [{ file: LIMITS, contains: "It is not reviewed, endorsed, used or validated by NASA, JPL or the MSL mission team." }],
  },
  {
    id: "lim_positions",
    category: "LIMITATION",
    short_claim: "Rover positions are PLACES interpolations — mostly the nearest pose within a drive, not per-frame onboard localization.",
    numbers: [],
    source_file: LIMITS,
    source_field_or_section: "PLACES interpolation",
    safe_public_wording: "Rover positions come from the PDS PLACES localization table, mostly the nearest pose within a drive — so distances are approximate.",
    scope: "All spatial metrics.",
    limitations: "",
    forbidden_wording: [],
    evidence: [{ file: LIMITS, contains: "Rover positions come from the PLACES localized_interp table" }],
  },

  // ───────────────────────── CONTEXT ─────────────────────────
  {
    id: "ctx_bandwidth_problem",
    category: "CONTEXT",
    short_claim: "A rover's instruments can produce more data than relay passes carry, so products are prioritized: full quality, thumbnail, later, or never.",
    numbers: [],
    source_file: PAPER,
    source_field_or_section: "§1 Introduction",
    safe_public_wording: "A Mars rover can collect more data than its relay passes can carry. Something has to decide what goes down at full quality, what goes as a thumbnail, and what waits.",
    scope: "Problem framing (background, not a DEEPSIFT result).",
    limitations: "",
    forbidden_wording: [],
    evidence: [{ file: PAPER, contains: "A Mars rover's imaging and environmental instruments can produce more data than relay passes carry" }],
  },
  {
    id: "ctx_public_data",
    category: "CONTEXT",
    short_claim: "All data are archived Curiosity Navcam products from NASA's public Planetary Data System (credit NASA/JPL-Caltech).",
    numbers: [],
    source_file: "apps/web/public/navcam/provenance.json",
    source_field_or_section: "credit / label",
    safe_public_wording: "The images are real archived Curiosity Navcam products from NASA's public Planetary Data System (image credit: NASA/JPL-Caltech).",
    scope: "All DEEPSIFT data.",
    limitations: "Site previews are contrast-stretched for display; not photometrically comparable.",
    forbidden_wording: ["live NASA feed", "live from Mars"],
    evidence: [{ file: "apps/web/public/navcam/provenance.json", path: ["credit"], fmt: "raw", expect: "NASA/JPL-Caltech · Mars Science Laboratory Navcam raw EDR (PDS Imaging Node, MSLNAV_0XXX)" }],
  },
  {
    id: "ctx_mission_control",
    category: "CONTEXT",
    short_claim: "Mission Control on deepsift.space is a historical replay of the frozen held-out results — not a live feed and not rover control.",
    numbers: [],
    source_file: MC,
    source_field_or_section: "label (HISTORICAL REPLAY)",
    safe_public_wording: "Mission Control replays the frozen held-out test frame by frame. It is a historical replay of archived data — never a live feed.",
    scope: "deepsift.space/mission-control.",
    limitations: "Display previews are for visualization only.",
    forbidden_wording: ["live mission control", "control Curiosity"],
    evidence: [{ file: MC, path: ["label"], fmt: "raw", expect: "HISTORICAL REPLAY · Curiosity Navcam · sols 950–979 · held-out test" }],
  },
  {
    id: "ctx_what_worked",
    category: "ENGINEERING",
    short_claim: "What generalized: farthest-point sampling on rover position plus a scheduler that fills thumbnails, then compressed, then full images, never splitting a stereo pair.",
    numbers: [],
    source_file: PAPER,
    source_field_or_section: "§4 System architecture",
    safe_public_wording: "What survived: pick frames that spread out along the rover's path (farthest-point sampling on position), and schedule thumbnails first, then full pairs, never one eye alone.",
    scope: "Primary path of the v1 release.",
    limitations: HEADLINE_LIMITS,
    forbidden_wording: [],
    evidence: [{ file: PAPER, contains: "farthest-point sampling [7] on the Euclidean\n   distance between PLACES positions" }],
  },
];

export const FACT_BY_ID: Record<string, VerifiedFact> = Object.fromEntries(VERIFIED_FACTS.map((f) => [f.id, f]));

/** Facts whose numbers are the headline — any post quoting them needs scope and archived-data context. */
export const HEADLINE_FACT_IDS = ["held_out_bytes", "held_out_coverage", "held_out_max_distance", "held_out_stereo"];
