#!/usr/bin/env python3
"""Derive detector thresholds from the CALIBRATION split only → config/phase2.yaml.

Label-free: no synthetic injections, no documented events, no strategy outcomes are read. The only
inputs are the calibration sols' raw data and the target flag rates in config/calibration_targets.yaml.
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import polars as pl
import yaml

from deepsift.adapters.curiosity import CHANNELS, CuriosityAdapter
from deepsift.core.config import CONFIG_DIR, DATA_DIR, load_config
from deepsift.features.extract import add_baselines, window_stats

ROOT = CONFIG_DIR.parent


def split_sols(name: str) -> list[int]:
    spec = json.loads((DATA_DIR / "splits" / "splits.json").read_text())["splits"][name]
    sols: list[int] = []
    for seg in spec["segments"]:
        sols += list(range(seg["eval"][0], seg["eval"][1] + 1))
    return sols


def main() -> None:
    targets = yaml.safe_load((CONFIG_DIR / "calibration_targets.yaml").read_text())
    base = load_config()
    sols = split_sols(targets["split"])
    a = CuriosityAdapter(window_s=base.detection.rems_window_s)
    a.load(sols)
    m = a.normalize()
    instruments = sorted(m.samples["instrument"].unique().to_list())
    w0 = window_stats(m.samples, {i: a.window_key(i) for i in instruments}, base.detection.lmst_bin_minutes)

    # 1) per-channel noise floor = the sensor's own measurement noise, σ ≈ robust std(Δ)/√2 of consecutive
    #    samples while the channel is active (REMS: within windows; RAD: consecutive integrations).
    floors = {}
    for ch, part in m.samples.sort("t").group_by("channel"):
        d = part["value"].diff().drop_nulls().to_numpy()
        d = d[d != 0] if ch[0] == "uv_abc" else d          # UV is exactly 0 at night; ignore inactive periods
        mad = np.median(np.abs(d - np.median(d))) if len(d) else 0.0
        floors[ch[0]] = float(1.4826 * mad / np.sqrt(2)) or next(c.min_sigma for c in CHANNELS if c.name == ch[0])

    # 2) recompute features with the derived floors, then quantiles for the target flag rates
    w = add_baselines(w0, CHANNELS, base.detection.baseline_sols, min_sigma_override=floors)
    tw = w.filter(pl.col("baseline_mode") == "trailing")
    tr = targets["target_flag_rate"]
    q = lambda s, rate: float(np.quantile(s.drop_nulls().to_numpy(), 1 - rate))  # noqa: E731
    z_rems = q(tw.filter(pl.col("instrument") == "REMS")["robust_z"].abs(), tr["level"])
    z_rad = q(tw.filter(pl.col("instrument") == "RAD")["robust_z"].abs(), tr["level"])
    dip = q(tw.filter(pl.col("channel") == "pressure")["dip"], tr["dip"])
    noise = q(tw.filter(pl.col("n") >= base.detection.min_samples)["noise_ratio"], tr["noise"])

    derived = {
        "z_threshold": round(z_rems, 3), "rad_z_threshold": round(z_rad, 3), "dip_threshold_pa": round(dip, 3),
        "noise_ratio_threshold": round(noise, 3), "min_sigma": {k: round(v, 5) for k, v in sorted(floors.items())},
        "flat_fraction_threshold": targets["structural"]["flat_fraction_threshold"],
        "missing_fraction_threshold": targets["structural"]["missing_fraction_threshold"],
    }
    cfg = base.patched({"detection": derived})
    products = sorted(m.metadata.products)
    manifest = json.loads((DATA_DIR / "raw" / "manifest.json").read_text())["files"]
    hashes = {k: v["sha256"] for k, v in manifest.items() if any(k.endswith(pn) or pn in k for pn in products)}
    cfg = cfg.patched({"provenance": {
        "calibration": {
            "script": "scripts/calibrate.py", "at": datetime.now(timezone.utc).isoformat(), "split": targets["split"],
            "sols": [sols[0], sols[-1]], "targets": targets, "trailing_windows_used": tw.height,
            "v0_1_values": {k: getattr(base.detection, k) for k in ("z_threshold", "rad_z_threshold", "dip_threshold_pa", "noise_ratio_threshold")},
            "data_sha256_digest": hashlib.sha256(json.dumps(hashes, sort_keys=True).encode()).hexdigest(),
            "labels_read": False, "injections_used": False,
        },
    }})
    out = CONFIG_DIR / "phase2.yaml"
    out.write_text("# GENERATED by scripts/calibrate.py — do not edit detection values by hand.\n"
                   + yaml.safe_dump(cfg.model_dump(mode="json"), sort_keys=False, allow_unicode=True))
    print(json.dumps(derived, indent=1))
    print(f"v0.1 hand-set values: {cfg.provenance['calibration']['v0_1_values']}")
    print(f"wrote {out.relative_to(ROOT)} · config version {cfg.version()}")


if __name__ == "__main__":
    main()
