#!/usr/bin/env python3
"""Phase-2 study CLI.

    uv run python scripts/run_study.py --split validation            # sweeps + choices
    uv run python scripts/run_study.py --freeze <validation_run_id>  # apply the pre-declared selection rule
    uv run python scripts/run_study.py --split test                  # refuses unless the config is frozen

Jev strategies are OFF by default since phase2-complete (stop rule). `--experimental-jev` re-enables them for
reproducibility; they then also need OPENROUTER_API_KEY and a passing scripts/jev_smoke.py.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "services" / "pipeline"))

from deepsift.core.config import load_config  # noqa: E402
from deepsift.decision.jev import jev_available, missing_key_instructions  # noqa: E402
from deepsift.evaluation.study import Study, load_env_and_check  # noqa: E402

PHASE2 = ROOT / "config" / "phase2.yaml"

# Declared before any validation result was computed (Phase 2):
SELECTION_RULE = ("Among Pareto-optimal (auto, uncertain) gating thresholds on VALIDATION synthetic data, keep those that "
                  "would escalate ≤ 25 % of candidate events; choose the one with the highest high-severity tolerant recall; "
                  "break ties by precision (lower bound), then by fewer downlinked bytes.")


def freeze(run_id: str) -> None:
    res = json.loads((ROOT / "artifacts" / "runs" / run_id / "results.json").read_text())
    if res["split"] != "validation":
        raise SystemExit("freeze must use a validation run")
    cfg_doc = yaml.safe_load(PHASE2.read_text())
    choices = {}
    for key, pts in res["gating"].items():
        dataset, engine = key.split(":", 1)
        if dataset != "synthetic":
            continue
        ok = [p for p in pts if p["pareto"] and p["would_escalate"] <= 0.25 * p["events"]]
        if not ok:
            continue
        best = sorted(ok, key=lambda p: (-p["high_tolerant_recall"], -p["precision_lower_bound"], p["downlink_bytes"]))[0]
        choices[engine] = {"auto_threshold": best["auto"], "uncertain_threshold": best["uncertain"], "validation_point": best}
    prov = cfg_doc.get("provenance") or {}
    prov["validation_choices"] = {"validation_run": run_id, "rule": SELECTION_RULE, "per_engine": choices,
                                  "frozen": True}
    cfg_doc["provenance"] = prov
    # the pipeline-wide gating default = the choice for the engine that will actually run
    primary = "JEV_NO_MISSION_OBJECTIVE" if "JEV_NO_MISSION_OBJECTIVE" in choices else "MOCK"
    if primary in choices:
        cfg_doc["gating"]["auto_threshold"] = choices[primary]["auto_threshold"]
        cfg_doc["gating"]["uncertain_threshold"] = choices[primary]["uncertain_threshold"]
        prov["validation_choices"]["applied_to_gating_defaults_from"] = primary
    PHASE2.write_text("# GENERATED by scripts/calibrate.py + run_study.py --freeze — do not edit by hand.\n"
                      + yaml.safe_dump(cfg_doc, sort_keys=False, allow_unicode=True))
    print(json.dumps(prov["validation_choices"], indent=1, default=str))


# Declared 2026-09-25, BEFORE any live Jev call (see docs/jev-model-selection.md):
JEV_SELECTION_RULE = (
    "Eligible variants: ≥ 99 % of validation requests returned parse-valid answers and < 2 % errors. "
    "Primary metric: mean VALIDATION synthetic high-severity tolerant recall over budgets 0.1, 0.25, 0.5 and 1 % "
    "(ENGINE_ONLY form; ENGINE_SINGLE_DECISION for the single-decision variant). Ties within 1 point → fewer input "
    "tokens per request, then lower p95 latency. Validation documented events (n = 6) are reported, not used. "
    "RULES_PLUS_JEV = the chosen variant's confidence-gated form with (auto, uncertain) from the declared gating rule."
)
LOW_BUDGETS = (0.001, 0.0025, 0.005, 0.01)


def freeze_jev(run_id: str) -> None:
    run = ROOT / "artifacts" / "runs" / run_id
    res = json.loads((run / "results.json").read_text())
    if res["split"] != "validation":
        raise SystemExit("the Jev selection must use a VALIDATION run")
    calls = [json.loads(line) for line in (run / "jev_calls.jsonl").read_text().splitlines()] if (run / "jev_calls.jsonl").exists() else []
    live = [c for c in calls if not c.get("cache_hit")]
    if not live and not calls:
        raise SystemExit("no Jev calls recorded for this run — nothing to select")
    curves = res["synthetic_curves"]
    table = {}
    for name, curve in curves.items():
        if not name.startswith("JEV_") or not (name.endswith("/ENGINE_ONLY") or name.endswith("/ENGINE_SINGLE_DECISION")):
            continue
        key = name.split("/")[0]
        variant = key[len("JEV_"):].lower()
        vcalls = [c for c in calls if c.get("variant") == variant]
        errs = sum(1 for c in vcalls if c.get("error"))
        ok = sum(1 for c in vcalls if not c.get("error") and (c.get("cache_hit") or c.get("answers")))
        tokens = [c["input_tokens"] for c in vcalls if c.get("input_tokens")]
        lat = sorted(c["latency_ms"] for c in vcalls if c.get("latency_ms") and not c.get("cache_hit"))
        vals = [curve[str(f)]["high_tolerant_recall"] if str(f) in curve else curve[f]["high_tolerant_recall"] for f in LOW_BUDGETS]
        table[variant] = {"strategy": name, "mean_high_recall_low_budgets": sum(vals) / len(vals), "per_budget": dict(zip(map(str, LOW_BUDGETS), vals)),
                          "requests": len(vcalls), "errors": errs, "valid_fraction": ok / len(vcalls) if vcalls else 0.0,
                          "tokens_per_request": (sum(tokens) / len(tokens)) if tokens else None,
                          "p95_latency_ms": lat[int(0.95 * (len(lat) - 1))] if lat else None}
    eligible = {v: t for v, t in table.items() if t["valid_fraction"] >= 0.99 and (t["errors"] / max(t["requests"], 1)) < 0.02}
    if not eligible:
        raise SystemExit(f"no eligible Jev variant: {json.dumps(table, indent=1)}")
    best = max(t["mean_high_recall_low_budgets"] for t in eligible.values())
    tied = [v for v, t in eligible.items() if best - t["mean_high_recall_low_budgets"] <= 0.01]
    tied.sort(key=lambda v: (eligible[v]["tokens_per_request"] or 1e9, eligible[v]["p95_latency_ms"] or 1e9))
    primary = tied[0]
    import subprocess as sp

    commit = sp.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip()
    cfg_doc = yaml.safe_load(PHASE2.read_text())
    prov = cfg_doc.get("provenance") or {}
    gating = (prov.get("validation_choices") or {}).get("per_engine", {})
    prov["jev_selection"] = {"frozen": True, "validation_run": run_id, "rule": JEV_SELECTION_RULE, "primary_variant": primary,
                             "primary_strategy": table[primary]["strategy"], "rules_plus_jev_strategy": f"JEV_{primary.upper()}/RULES_PLUS_ENGINE",
                             "rules_plus_jev_gating": gating.get(f"JEV_{primary.upper()}"), "table": table, "tied": tied,
                             "commit_at_freeze": commit}
    cfg_doc["provenance"] = prov
    PHASE2.write_text("# GENERATED by scripts/calibrate.py + run_study.py --freeze/--freeze-jev — do not edit by hand.\n"
                      + yaml.safe_dump(cfg_doc, sort_keys=False, allow_unicode=True))
    print(json.dumps(prov["jev_selection"], indent=1, default=str))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--split", choices=["calibration", "validation", "test"])
    ap.add_argument("--batches", type=int, default=25)
    ap.add_argument("--experimental-jev", action="store_true",
                    help="opt in to the discontinued Jev ranking strategies (Phase 2 stop rule; reproducibility only)")
    ap.add_argument("--no-jev", action="store_true", help="kept for old commands; Jev is already off by default")
    ap.add_argument("--experiments", default="real,synthetic,storage,gating,calibration")
    ap.add_argument("--freeze", metavar="VALIDATION_RUN_ID")
    ap.add_argument("--freeze-jev", metavar="VALIDATION_RUN_ID")
    ap.add_argument("--jev-variants", default=None, help="comma list (validation only); test uses the frozen selection")
    ap.add_argument("--no-cache", action="store_true", help="research only: bypass the Jev cache (every call is live)")
    ap.add_argument("--allow-calls", type=int, default=None)
    ap.add_argument("--allow-cost", type=float, default=None)
    args = ap.parse_args()
    load_env_and_check()
    if args.freeze:
        freeze(args.freeze)
        return 0
    if args.freeze_jev:
        freeze_jev(args.freeze_jev)
        return 0
    cfg = load_config(PHASE2)
    if args.split == "test" and not (cfg.provenance or {}).get("validation_choices", {}).get("frozen"):
        raise SystemExit("refusing to evaluate TEST: config/phase2.yaml has no frozen validation choices (run --freeze first)")
    use_jev = args.experimental_jev and not args.no_jev      # Jev left the default path at phase2-complete
    budget = None
    variants = args.jev_variants.split(",") if args.jev_variants else None
    if use_jev:
        sel = (cfg.provenance or {}).get("jev_selection") or {}
        if args.split == "test":
            if not sel.get("frozen"):
                raise SystemExit("refusing Jev on TEST: no frozen Jev selection (run --freeze-jev on a validation run first)")
            if variants and variants != [sel["primary_variant"]]:
                raise SystemExit("on TEST only the frozen primary Jev configuration may run; ablations are validation-only")
            variants = [sel["primary_variant"]]
        if not jev_available():
            print(missing_key_instructions())
            print("→ continuing with every non-Jev strategy; Jev strategies are reported UNAVAILABLE.\n")
        else:
            from deepsift.decision.jev import ApiBudget, VARIANTS
            from deepsift.decision.jev_cache import JevCache
            from deepsift.evaluation.jev_plan import build_plan, fmt_summary, guard, limits_from_env

            plan, _ = build_plan(cfg, "test" if args.split == "test" else "validation", variants or list(VARIANTS),
                                 batches=args.batches, split=args.split)
            summ = plan.summary(None if args.no_cache else JevCache())
            max_calls, max_cost = limits_from_env()
            ok, why = guard(summ, max_calls, max_cost, args.allow_calls, args.allow_cost)
            print(fmt_summary(summ))
            print(f"GUARD {'OK' if ok else 'BLOCKED'} — {why}")
            if not ok:
                raise SystemExit(3)
            budget = ApiBudget(args.allow_calls or max_calls, args.allow_cost or max_cost)
            rc = subprocess.call([sys.executable, str(ROOT / "scripts" / "jev_smoke.py")])
            if rc != 0:
                print("Jev smoke test failed → Jev strategies disabled for this run.")
                use_jev = False
    st = Study(cfg, args.split, n_batches=args.batches, use_jev=use_jev, jev_variants=variants,
               experiments=set(args.experiments.split(",")), budget=budget, use_cache=not args.no_cache)
    out = st.run()
    print(f"run {st.run_id} → {out.relative_to(ROOT)}  (jev: {st.jev_status})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
