#!/usr/bin/env python3
"""Phase-2 study CLI.

    uv run python scripts/run_study.py --split validation            # sweeps + choices
    uv run python scripts/run_study.py --freeze <validation_run_id>  # apply the pre-declared selection rule
    uv run python scripts/run_study.py --split test                  # refuses unless the config is frozen

Jev strategies run only if TYPESAFE_API_KEY is set AND scripts/jev_smoke.py passes first.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "services" / "pipeline"))

from deepsift.core.config import load_config  # noqa: E402
from deepsift.decision.jev import jev_available, missing_key_instructions  # noqa: E402
from deepsift.evaluation.study import Study, load_env_and_check  # noqa: E402

PHASE2 = ROOT / "config" / "phase2.yaml"

# Declared before any validation result was computed (Phase 2):
SELECTION_RULE = ("Among Pareto-optimal (auto, uncertain) gating thresholds on VALIDATION synthetic data, keep those that "
                  "would escalate ≤ 25 % of candidate events; choose the one with the highest high-severity tolerant recall; "
                  "break ties by precision (lower bound), then by fewer downlinked bytes.")


def freeze(run_id: str) -> None:
    res = json.loads((ROOT / "artifacts" / "runs" / run_id / "results.json").read_text())
    if res["split"] != "validation":
        raise SystemExit("freeze must use a validation run")
    cfg_doc = yaml.safe_load(PHASE2.read_text())
    choices = {}
    for key, pts in res["gating"].items():
        dataset, engine = key.split(":", 1)
        if dataset != "synthetic":
            continue
        ok = [p for p in pts if p["pareto"] and p["would_escalate"] <= 0.25 * p["events"]]
        if not ok:
            continue
        best = sorted(ok, key=lambda p: (-p["high_tolerant_recall"], -p["precision_lower_bound"], p["downlink_bytes"]))[0]
        choices[engine] = {"auto_threshold": best["auto"], "uncertain_threshold": best["uncertain"], "validation_point": best}
    prov = cfg_doc.get("provenance") or {}
    prov["validation_choices"] = {"validation_run": run_id, "rule": SELECTION_RULE, "per_engine": choices,
                                  "frozen": True}
    cfg_doc["provenance"] = prov
    # the pipeline-wide gating default = the choice for the engine that will actually run
    primary = "JEV_NO_MISSION_OBJECTIVE" if "JEV_NO_MISSION_OBJECTIVE" in choices else "MOCK"
    if primary in choices:
        cfg_doc["gating"]["auto_threshold"] = choices[primary]["auto_threshold"]
        cfg_doc["gating"]["uncertain_threshold"] = choices[primary]["uncertain_threshold"]
        prov["validation_choices"]["applied_to_gating_defaults_from"] = primary
    PHASE2.write_text("# GENERATED by scripts/calibrate.py + run_study.py --freeze — do not edit by hand.\n"
                      + yaml.safe_dump(cfg_doc, sort_keys=False, allow_unicode=True))
    print(json.dumps(prov["validation_choices"], indent=1, default=str))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--split", choices=["calibration", "validation", "test"])
    ap.add_argument("--batches", type=int, default=25)
    ap.add_argument("--no-jev", action="store_true")
    ap.add_argument("--experiments", default="real,synthetic,storage,gating,calibration")
    ap.add_argument("--freeze", metavar="VALIDATION_RUN_ID")
    args = ap.parse_args()
    load_env_and_check()
    if args.freeze:
        freeze(args.freeze)
        return 0
    cfg = load_config(PHASE2)
    if args.split == "test" and not (cfg.provenance or {}).get("validation_choices", {}).get("frozen"):
        raise SystemExit("refusing to evaluate TEST: config/phase2.yaml has no frozen validation choices (run --freeze first)")
    use_jev = not args.no_jev
    if use_jev:
        if not jev_available():
            print(missing_key_instructions())
            print("→ continuing with every non-Jev strategy; Jev strategies are reported UNAVAILABLE.\n")
        else:
            rc = subprocess.call([sys.executable, str(ROOT / "scripts" / "jev_smoke.py")])
            if rc != 0:
                print("Jev smoke test failed → Jev strategies disabled for this run.")
                use_jev = False
    st = Study(cfg, args.split, n_batches=args.batches, use_jev=use_jev, experiments=set(args.experiments.split(",")))
    out = st.run()
    print(f"run {st.run_id} → {out.relative_to(ROOT)}  (jev: {st.jev_status})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
